#!/usr/bin/env bash
# lib/installer.sh — SPECTRA File Placement Engine
# Orchestrates the full installation:
#   1. Creates .spectra/ working directory
#   2. Generates project profile and adaptation prompt
#   3. Creates conventions stub
#   4. Delegates vendor-specific file placement to the selected adapter
#
# SPECTRA v4.2.0 — https://github.com/Rynaro/SPECTRA
# License: CC BY-SA 4.0

[[ -n "${_SPECTRA_INSTALLER_LOADED:-}" ]] && return 0
readonly _SPECTRA_INSTALLER_LOADED=1

run_installer() {
  local vendor="$SELECTED_VENDOR"
  local mode="$SELECTED_MODE"
  local fit_only="${SPECTRA_FIT_ONLY:-false}"

  if [[ "$fit_only" == "true" ]]; then
    tui_section "Fitting SPECTRA"
  else
    tui_section "Installing SPECTRA"
  fi

  check_write_permission "$PROJECT_ROOT"

  _install_spectra_dir
  _generate_project_profile
  _generate_adaptation_prompt
  _install_conventions_stub

  # Vendor install only runs in full-install mode. The fit-only path
  # assumes the SPECTRA methodology is already wired through some other
  # mechanism (e.g. the eidolons installer) — we only need the project-
  # fit artefacts under .spectra/setup/.
  if [[ "$fit_only" != "true" ]]; then
    vendor_install "$vendor" "$mode"
  fi

  if [[ "$fit_only" == "true" ]]; then
    log_ok "Fit complete."
  else
    log_ok "Installation complete."
  fi
}

# ─── .spectra/ working directory ─────────────────────────────────────────────
_install_spectra_dir() {
  local spectra_dir="${PROJECT_ROOT}/${SPECTRA_DIR}"
  local plans_dir="${PROJECT_ROOT}/${SPECTRA_PLANS_DIR}"
  local setup_dir="${PROJECT_ROOT}/${SPECTRA_SETUP_DIR}"

  if [[ ! -d "$spectra_dir" ]]; then
    mkdir -p "$plans_dir" "$setup_dir"
    track_created "$spectra_dir"
    log_ok "Created: ${spectra_dir}/"
  else
    mkdir -p "$plans_dir" "$setup_dir"
  fi
  INSTALLED_FILES+=("${spectra_dir}/|SPECTRA working directory")
}

# ─── Project profile ──────────────────────────────────────────────────────────
_generate_project_profile() {
  local out="${PROJECT_ROOT}/${PROFILE_OUT}"

  if [[ -f "$out" ]]; then
    tui_confirm "project-profile.md already exists. Regenerate?" "y" || return 0
  fi

  local file_count
  file_count=$(find "${PROJECT_ROOT}" -type f \
    -not -path '*/\.*' -not -path '*/node_modules*' \
    -not -path '*/vendor*' -not -path '*/target*' 2>/dev/null | wc -l | tr -d ' ')

  local dir_tree
  dir_tree=$(find "${PROJECT_ROOT}" -maxdepth 3 -type d \
    -not -path '*/\.*' -not -path '*/node_modules*' -not -path '*/vendor*' \
    -not -path '*/__pycache__*' -not -path '*/target*' -not -path '*/dist*' \
    -not -path '*/build*' -not -path '*/.next*' -not -path '*/tmp*' \
    -not -path '*/log*' -not -path '*/coverage*' \
    2>/dev/null | sort | head -50 | sed "s|^${PROJECT_ROOT}/||" | sed 's|^\./||')

  local naming_samples
  naming_samples=$(find "${PROJECT_ROOT}" -maxdepth 4 -type f \
    \( -name "*.rb" -o -name "*.py" -o -name "*.ts" -o -name "*.js" \
       -o -name "*.go" -o -name "*.rs" -o -name "*.java" -o -name "*.kt" \
       -o -name "*.ex" -o -name "*.php" \) \
    -not -path '*/test*' -not -path '*/spec*' \
    -not -path '*/node_modules*' -not -path '*/vendor*' \
    2>/dev/null | head -15 | sed "s|^${PROJECT_ROOT}/||" | sort)

  local convention_summary
  convention_summary=$(get_convention_summary 2>/dev/null || echo "None detected")

  cat > "$out" <<PROFILE_EOF
# SPECTRA Project Profile

> Generated by spectra-init.sh v${SPECTRA_VERSION} on $(date -u +%Y-%m-%d)
> Project: **${PROJECT_NAME}**

## Stack

| Aspect | Detected |
|--------|----------|
| Languages | ${DETECTION_RESULT_LANGUAGE:-Unknown} |
| Frameworks | ${DETECTION_RESULT_FRAMEWORK:-Not detected} |
| Test Frameworks | ${DETECTION_RESULT_TEST:-Not detected} |
| Build / Package | ${DETECTION_RESULT_BUILD:-Not detected} |
| CI/CD | ${DETECTION_RESULT_CI:-Not detected} |
| Database | ${DETECTION_RESULT_DATABASE:-Not detected} |
| Architecture | ${DETECTION_RESULT_ARCHITECTURE:-Not detected} |
| Files | ~${file_count} |

## Convention Files Detected

${convention_summary}

## Directory Structure (top 3 levels)

\`\`\`
${dir_tree}
\`\`\`

## Naming Samples

\`\`\`
${naming_samples}
\`\`\`

## Next Step

Paste **${PROMPT_OUT}** into your preferred LLM to generate SPECTRA conventions for this project.

*SPECTRA v${SPECTRA_VERSION} — ${SPECTRA_REPO}*
PROFILE_EOF

  track_created "$out"
  INSTALLED_FILES+=("${out}|Project profile (detected stack)")
  log_ok "Generated: ${out}"
}

# ─── Adaptation prompt ────────────────────────────────────────────────────────
_generate_adaptation_prompt() {
  local out="${PROJECT_ROOT}/${PROMPT_OUT}"

  if [[ -f "$out" ]]; then
    tui_confirm "adaptation-prompt.md already exists. Regenerate?" "y" || return 0
  fi

  local dir_tree
  dir_tree=$(find "${PROJECT_ROOT}" -maxdepth 3 -type d \
    -not -path '*/\.*' -not -path '*/node_modules*' -not -path '*/vendor*' \
    -not -path '*/__pycache__*' -not -path '*/target*' \
    2>/dev/null | sort | head -30 | sed "s|^${PROJECT_ROOT}/||" | sed 's|^\./||')

  local naming_samples
  naming_samples=$(find "${PROJECT_ROOT}" -maxdepth 4 -type f \
    \( -name "*.rb" -o -name "*.py" -o -name "*.ts" -o -name "*.js" \
       -o -name "*.go" -o -name "*.rs" -o -name "*.java" -o -name "*.kt" \
       -o -name "*.ex" -o -name "*.php" \) \
    -not -path '*/test*' -not -path '*/spec*' \
    -not -path '*/node_modules*' -not -path '*/vendor*' \
    2>/dev/null | head -15 | sed "s|^${PROJECT_ROOT}/||" | sort)

  cat > "$out" <<PROMPT_EOF
# SPECTRA Stack Adaptation Prompt

> Copy this entire file and paste into your preferred LLM (Claude, GPT, Gemini, Llama, etc.).
> It will generate a conventions file mapping SPECTRA's generic vocabulary to your project.

---

## Context

I'm adopting **SPECTRA** (${SPECTRA_REPO}), a vendor-agnostic planning methodology for AI-assisted software specification. SPECTRA uses generic terminology (Service Objects, Repository Pattern, etc.). I need you to map these concepts to my project's specific conventions so that SPECTRA-generated specs use the right vocabulary for my codebase.

## My Project

| Aspect | Value |
|--------|-------|
| Project | ${PROJECT_NAME} |
| Languages | ${DETECTION_RESULT_LANGUAGE:-Unknown} |
| Frameworks | ${DETECTION_RESULT_FRAMEWORK:-Not detected} |
| Tests | ${DETECTION_RESULT_TEST:-Not detected} |
| Build | ${DETECTION_RESULT_BUILD:-Not detected} |
| CI/CD | ${DETECTION_RESULT_CI:-Not detected} |
| Database | ${DETECTION_RESULT_DATABASE:-Not detected} |
| Architecture | ${DETECTION_RESULT_ARCHITECTURE:-Not detected} |

### Directory Structure
\`\`\`
${dir_tree}
\`\`\`

### Naming Samples
\`\`\`
${naming_samples}
\`\`\`

## Generate These Sections

### 1. Convention Mapping

Map SPECTRA generic concepts to my project. Fill "My Convention" and "Path Pattern":

| SPECTRA Concept | Generic Example | My Convention | Path Pattern |
|----------------|-----------------|---------------|--------------|
| Service / Business Logic | \`UserRegistrationService\` | ? | ? |
| Data Access / Repository | \`UserRepository\` | ? | ? |
| Schema / Validation | \`UserSchema\` | ? | ? |
| UI Component | \`UserProfile\` | ? | ? |
| Background Job | \`ImportJob\` | ? | ? |
| API Endpoint | \`POST /users\` | ? | ? |
| Database Migration | \`add_users_table\` | ? | ? |
| Test File | \`user.test.ts\` | ? | ? |

### 2. Action Verb Mapping

SPECTRA stories use verbs: Create, Extend, Modify, Test, Configure, Migrate. Map each to my stack:

| Verb | In My Project | Example |
|------|--------------|---------|
| Create | ? | "Create \`?\` at \`?\`" |
| Extend | ? | "Extend \`?\` with \`?\`" |
| Modify | ? | "Modify \`?\` to \`?\`" |
| Test | ? | "Test with \`?\` covering \`?\`" |
| Configure | ? | "Configure \`?\` in \`?\`" |
| Migrate | ? | "Migrate \`?\` using \`?\`" |

### 3. Validation Gates Template

Standard P0/P1/P2 gates for my project:

\`\`\`markdown
## Agent Hints:
- **Class:** [builder/reasoner/debugger]
- **Context:** [path to exemplar]
- **Gates:**
  - [ ] P0: [my critical gate]
  - [ ] P1: [my test gate]
  - [ ] P2: [my lint gate]
\`\`\`

### 4. Example Story

Write a complete SPECTRA story for: **"Add a health check endpoint returning service status and version"** using my project's actual conventions, paths, and patterns.

### 5. Project-Specific Rules

Based on my architecture, what constraints should every SPECTRA spec follow?

### 6. Artifact Storage

Where should SPECTRA store planning artifacts in my project?

\`\`\`
${PROJECT_NAME}/
├── .spectra/plans/        # .md, .yaml, .state.json
└── .spectra/setup/        # profile, prompt, conventions
\`\`\`

## Output

Single Markdown file: \`spectra-conventions.md\`

Start with a **Quick Reference** (5 most important conventions for this project), then all sections above.

*Prompt generated by SPECTRA v${SPECTRA_VERSION}*
PROMPT_EOF

  track_created "$out"
  INSTALLED_FILES+=("${out}|Adaptation prompt (paste into any LLM)")
  log_ok "Generated: ${out}"
}

# ─── Conventions stub ─────────────────────────────────────────────────────────
_install_conventions_stub() {
  local target="${PROJECT_ROOT}/${SPECTRA_SETUP_DIR}/spectra-conventions.md"

  # Don't overwrite if it already has content beyond the stub header
  if [[ -f "$target" ]]; then
    return 0
  fi

  local stub
  stub=$(cat "${SPECTRA_HOME}/assets/templates/conventions-stub.md")
  stub="${stub//\{\{PROJECT_NAME\}\}/$PROJECT_NAME}"
  stub="${stub//\{\{SPECTRA_VERSION\}\}/$SPECTRA_VERSION}"
  stub="${stub//\{\{DATE\}\}/$(date -u +%Y-%m-%d)}"
  stub="${stub//\{\{SPECTRA_REPO\}\}/$SPECTRA_REPO}"
  stub="${stub//\{\{PROJECT_ROOT\}\}/$PROJECT_NAME}"

  echo "$stub" > "$target"
  track_created "$target"
  INSTALLED_FILES+=("${target}|Conventions stub (fill after running adaptation prompt)")
  log_ok "Created: ${target}"
}
